refactor map unmap

diff --git a/scripts/mapunmap b/scripts/mapunmap
--- a/scripts/mapunmap
+++ b/scripts/mapunmap
@@ -3,31 +3,36 @@
 
 ### MAIN ###
 
+criteria=""
+
 # The most robust getopt
-args=$(getopt -q -o c:f: -l "classname:,first:" -n "$(basename $0)" -- "$@")
-test $# -lt 2 -o $? -ne 0 && printf "usage: -c classname command\n" && exit 1
+args=$(getopt -q -o n:N:t:f: -l "instance:,class:,title:,first:" -n "$(basename $0)" -- "$@")
+test $? -ne 0 && printf "usage: -c instance command\n" && exit 1
 eval set -- "$args"; while true; do
     case "$1" in
-        -c|--classname) shift; classname=$1; shift ;;
+        -n|--instance) shift; criteria="${criteria} -n $1"; shift ;;
+        -N|--class) shift; criteria="${criteria} -N $1"; shift ;;
+        -t|--title) shift; criteria="${criteria} -t $1"; shift ;;
         -f|--first) shift; first=$1; shift ;;
         --) shift; break ;;
     esac
 done # $@ will store all remaing args
 
-# assume that all 'mapunmap' window are floating
-bspc rule -a ${classname} -o floating=on
+base="xdo id"
+wactive=$($base)
+wtarget=$(eval "${base} ${criteria}")
 
-
-if xdotool search --onlyvisible --classname ${classname} windowunmap; then
-    #echo "window is enabled, disable it" >> /tmp/.mapunmap.log
-    true
+if [ "$?" -ne 0 ]; then # no target windows found
+    #echo "window target is not found, launch window"
+    eval "$@"
+    [ ! -z $first ] && eval "$first"
 else
-    if xdotool search --classname ${classname} windowmap; then
-        #echo "window is disabled, enable it" >> /tmp/.mapunmap.log
-        true
+    if echo $wtarget | grep -q $wactive; then
+        #echo "window target is found at ${wtarget}, and shown, thus hide it"
+        echo ${wtarget} | xargs xdo hide
     else
-        #echo "create window first time with cmd: $@" >> /tmp/.mapunmap.log
-        eval "$@"
-        [ ! -z $first ] && eval "$first"
+        #echo "window target is found at ${wtarget}, and hidden, thus re-show it"
+        echo ${wtarget} | xargs xdo hide
+        echo ${wtarget} | xargs xdo show
     fi
 fi
